# Generated by Django 5.1 on 2024-08-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_mensaje_fecha_hora_mensaje_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='texto',
            field=models.TextField(),
        ),
    ]
